config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'login#show'

  get '/status', to: 'status#show'
  post '/githook', to: 'githook#hook'
  get '/login', to: 'login#show'
  resource :session, only: %i[create destroy]
  resource :settings, only: %i[show update], controller: 'user_settings'
  resources :todo_lists do
    resources :todos
  end
  resource :registration, only: %i[show create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  belongs_to :todo_list

  validates :todo_list, presence: true
  validates :description, presence: true
end

app/models/todo_list.rb
# frozen_string_literal: true

class TodoList < ApplicationRecord
  has_many :todos, dependent: :destroy
  belongs_to :user

  validates :label, presence: true
  validates :user, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :password, length: { in: 8..20 }
  validates :email, presence: true

  has_many :todo_lists, dependent: :destroy
  has_many :todos, through: :todo_lists

  after_create :create_default_list

  def create_default_list
    todo_list = TodoList.create!(label: 'Daily', user: self)
    Todo.create!(description: 'Get Started!', todo_list: todo_list)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/githook_controller.rb
# frozen_string_literal: true

class GithookController < ApplicationController
  skip_before_action :verify_authenticity_token

  def hook
    head :ok
  end
end

app/controllers/login_controller.rb
# frozen_string_literal: true

class LoginController < ApplicationController
  before_action :authenticated?

  def show; end

  private

  def authenticated?
    redirect_to todo_list_todos_path(current_user.todo_lists.first) if logged_in?
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  def create
    user = User.find_by(email: registration_params[:email])

    if user
      redirect_to registration_path, notice: 'This user already exists'
    else
      user = User.create!(email: registration_params[:email], password: registration_params[:password])
      log_in(user)
      redirect_to todo_list_todos_path(user.todo_lists.first)
    end
  end

  def show; end

  private

  def registration_params
    params.permit(:email, :password)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    if user.authenticate(permitted[:password]).present?
      log_in(user)
      redirect_to todo_list_todos_path(user.todo_lists.first)
      return
    end

    head :no_content
  end

  def destroy
    log_out
    redirect_to login_path
  end

  def permitted
    params.permit(:email, :password)
  end

  private

  def user
    @user ||= User.find_by(email: permitted[:email])
  end
end

app/controllers/status_controller.rb
# frozen_string_literal: true

class StatusController < ApplicationController
  def show
    head :ok
  end
end

app/controllers/todo_lists_controller.rb
# frozen_string_literal: true

class TodoListsController < ApplicationController
  before_action :authenticate_user

  def index
    @todo_lists = current_user.todo_lists
  end

  def create
    @todo_list = TodoList.new(
      label: todo_list_params[:label],
      user: current_user
    )

    respond_to do |format|
      format.turbo_stream do
        if @todo_list.save
          render turbo_stream: turbo_stream.append(:todo_lists, partial: 'shared/todo_list',
                                                                locals: { todo_list: @todo_list })
        end
      end
    end
  end

  def destroy
    @todo_list = todos_view.todo_lists.find(params[:id])
    @todo_list.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@todo_list) }
    end
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:label)
  end

  def todos_view
    @todos_view ||= TodosView.new(current_user, params)
  end
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  include TodosHelper

  before_action :authenticate_user

  def index
    todos_view
  end

  def create
    @todo = Todo.new(
      description: todo_params[:description],
      todo_list: todos_view.todo_list
    )

    respond_to do |format|
      format.turbo_stream do
        if @todo.save
          render turbo_stream: turbo_stream.prepend(:todos, partial: 'todo',
                                                            locals: { todo: @todo })
        end
      end
    end
  end

  def update
    @todo = todos_view.todo_list.todos.find(params[:id])
    @todo.update!(completed_at: completed_at(todo_params))

    respond_to do |format|
      format.html { render todos_view.todo_list.todos }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@todo)
      end
    end
  end

  def destroy
    @todo = todos_view.todo_list.todos.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@todo) }
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:description, :completed_at)
  end

  def todos_view
    @todos_view ||= TodosView.new(current_user, params)
  end
end

app/controllers/user_settings_controller.rb
# frozen_string_literal: true

class UserSettingsController < ApplicationController
  before_action :authenticate_user

  def show; end

  def update
    if current_user.update(email: params[:email], password: params[:password])
      flash[:notice] = 'Settings updated!'
    else
      flash[:alert] = current_user.errors.full_messages
    end
    redirect_to settings_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/login_helper.rb
# frozen_string_literal: true

module LoginHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    session[:user_id].present?
  end

  def log_in(current_user)
    session[:user_id] = current_user.id
  end

  def log_out
    session[:user_id] = nil
  end

  def authenticate_user
    redirect_to login_url unless logged_in?
  end
end

app/helpers/todo_lists_helper.rb
# frozen_string_literal: true

module TodoListsHelper
end

app/helpers/todos_helper.rb
# frozen_string_literal: true

module TodosHelper
  def completed_at(params)
    params[:completed_at].to_i.positive? ? DateTime.current : nil
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DashyMcDashboard
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body.h-screen.flex.flex-col
    %main.flex.flex-col.grow
      = yield
    .md:hidden
      = render 'shared/mobile_footer'

app/views/login/show.html.haml
= render "shared/header"
.flex.flex-col.grow.items-center.pt-16
  %h1.pb-2.text-xl
    Welcome Back!
  = form_with url: "/session", method: :post, class: 'flex flex-col w-10/12 lg:w-2/5' do |form|
    = form.email_field :email, class: ['mb-2']
    = form.password_field :password, class: ['mb-2']
    = form.submit "Login", class: ['border-solid', 'border-2']

app/views/shared/_header.html.haml
.flex.p-5.border-t-8.justify-between{class: 'border-[#77a5ff]'}
  %h1.text-xl
    = link_to "Dashy McDashboard", root_path
  .hidden.md:flex
    - if logged_in?
      .flex
        .mr-2
          = button_to "Logout", session_path, method: :delete, class: ['text-[#5197ff]', 'hover:underline']
        %span /
        .ml-2
          = link_to "Settings", settings_path
    - else
      .flex
        = link_to "Register", registration_path
        %span /
        = link_to "Login", login_path

app/views/shared/_mobile_footer.html.haml
.flex.border.sticky
  %button.grow.border-r.pt-2.pb-2
    - if logged_in?
      = link_to "Lists", todo_lists_path
    - else
      = link_to "Register", registration_path
  .flex.grow.pt-2.pb-2.justify-center
    - if logged_in?
      = button_to "Logout", session_path, method: :delete
    - else
      = link_to "Login", login_path

app/views/shared/_todo_list.html.haml
= turbo_frame_tag dom_id(todo_list) do
  .flex.items-center.justify-between.mb-4
    = link_to todo_list.label, todo_list_todos_path(todo_list), target: '_top'
    = button_to todo_list_path(todo_list), method: :delete do
      %i.far.fa-trash-alt

app/views/todo_lists/_new_form.html.haml
.mb-8{data: { controller: 'todo'}}
  = form_with model: TodoList.new, data: {'todo-target' => 'form'} do |f|
    = f.text_field :label, data: { 'todo-target' => 'input' }, placeholder: 'New List...', autocomplete: 'off'

app/views/todo_lists/index.html.haml
.flex.h-full
  .flex-col.w-56.mt-5.grow{ class: "border-[#a9c6ff]" }
    .mb-5.px-5
      = render partial: "todo_lists/new_form"
      = turbo_frame_tag "todo_lists" do
        = render partial: "shared/todo_list", collection: @todo_lists

app/views/todos/_todo.html.haml
= turbo_frame_tag dom_id(todo) do
  .flex.justify-between.p-2.mb-1.border-b{class: [('line-through' if todo.completed_at), 'border-[#dbe7ff]']}
    .flex
      .px-2
        = form_with model: todo, url: todo_list_todo_path(@todos_view.todo_list, todo), method: "patch"  do |f|
          = f.check_box :completed_at, { onchange: "this.form.requestSubmit()", checked: todo.completed_at.present?, class: 'text-[#71cd74]' }
      = todo.description
    = button_to todo_list_todo_path(@todos_view.todo_list, todo), method: :delete do
      %i.far.fa-trash-alt

app/views/todos/_todo_input.html.haml
.pb-5
  = turbo_frame_tag dom_id(Todo.new), data: {'controller' => 'todo'} do
    = form_for([@todos_view.todo_list, Todo.new], data: {'todo-target' => 'form'}) do |f|
      = f.text_field :description, { class: 'w-full', data: { 'data-action' => 'click->todo#submitForm' }, placeholder: 'new todo...', autocomplete: 'off' }

app/views/todos/index.html.haml
.hidden.md:block
  = render "shared/header"
.flex.h-full
  .flex-col.w-56.mt-5.mb-5.border-r.hidden.md:flex{ class: "border-[#a9c6ff]" }
    .mb-5.px-5
      = render partial: "todo_lists/new_form"
      = turbo_frame_tag "todo_lists" do
        = render partial: "shared/todo_list", collection: @todos_view.todo_lists

  .flex-col.grow.px-2.mt-5.md:px-5
    = render partial: "todo_input"
    = turbo_frame_tag "todos" do
      = render partial: "todo", collection: @todos_view.todos

app/views/user_settings/show.html.haml
.hidden.md:block
  = render "shared/header"
.container.mx-auto.h-full.border.mb-8{class: 'w-2/4'}
  - if flash[:notice]
    .flex.flex-col.grow.items-center.bg-green-300.py-4
      = flash[:notice]
  - if flash[:alert]
    .flex.flex-col.grow.items-center.bg-red-300.py-4
      - flash[:alert].each do |alert|
        = alert
  .px-16
    .flex.flex-col.grow.pt-10.pb-10
      %h1.text-xl.mb-6 Settings
      = form_with model: @current_user, method: :PUT, class: 'flex flex-col grow w-full' do |form|
        = form.label :email, "Email:"
        = form.email_field :email, class: ['mb-2']
        = form.label :email, "Password:"
        = form.password_field :password, class: ['mb-2']
        = form.submit "Update Settings", class: ['border-solid', 'border-2']